### ISSUE TITLE
Dynamic updates

### ISSUE THREAD

**Issue by fbatibay** [dschnelldavis/angular2-json-schema-form#10]
Hi, thank you for great library,

I'm trying to make an dynamic select widget  (ajax or websocket powered - select with remote data for example), but when i bind data to widget, layout never updated. if i bind static data there is no problem at all, but if i bind after constructor (inside ngOnInit or setTimeout) relevant vars changing but layout never updating. 

i also tried, applicationref, ChangeDetectionStrategy and ngzone but i got no result.

Some details: 
I cloned library's select widget code from widgets folder and changed these lines,

```typescript
constructor(
    private jsf: JsonSchemaFormService,
    private ws: webSocketRequest,
  ){

  }

  ngOnInit() {

    this.options = this.layoutNode.options;

      this.ws.webSocketRequest("info", this.options.parameters , (value: any) => {

          this.selectList = value;
          this.jsf.initializeControl(this);

      });

  }
```

I looked default widgets code but no result yet, so can you give more detail to make a dynamic widget?

any helps appreciated.

**Comment by dschnelldavis** [comment]
Good question. I'm not sure.

You might be on to something with the ChangeDetectionStrategy though. The entire library is set to the "OnPush" ChangeDetectionStrategy, partly to make it faster, and partly because once a form is rendered it (theoretically) shouldn't need to be changed much. (Though what you're trying to do is an exception to that.)

To diagnose whether ChangeDetectionStrategy is the problem, edit src/library/json-schema-form.component.ts , and remove the following line:

```javascript
changeDetection: ChangeDetectionStrategy.OnPush,
```

Then restart your app. That will switch the change detection strategy for the library from OnPush back to Default, and make it detect changes for every event. If that fixes your problem, then you'll know your problem is with change detection. If it doesn't, then you'll know your problem is something else.

Also, try retrieving your external data as an observable, which should update independent of change detection. You can look at src/playground/playground.component.ts for one example of how to do this. The playground retrieves its example schemas and displays them by subscribing to an http observable. What the playground does barely scratches the surface of what you can do with observables though, so if you're new to using observables you'll probably also want to Google "RxJS" and "Angular2 Observables" for more information.

Let me know what you find out. And when you get it to work, please post how you finally fixed it, so other people who run into the same problem in the future will know.

Thanks!

-David

**Comment by fbatibay** [comment]
Thanks for your reply my friend.

**Comment by fbatibay** [comment]
_____

To diagnose whether ChangeDetectionStrategy is the problem, edit
src/library/json-schema-form.component.ts , and remove the following line:

changeDetection: ChangeDetectionStrategy.OnPush,

_____


this is solution of this problem. thanks again.

**Comment by fbatibay** [comment]
removing this line is solution. (and sorry for multiple post)

**Comment by dschnelldavis** [comment]
No problem about the multiple posts. I'm glad your control works with the Default the change detection strategy. That may be an adequate solution for now, so I'll close this issue. But in the long-run your application will run faster if you re-enable OnPush.

Ideally, I suspect the most efficient way to make your control work with the OnPush strategy is by retrieving your data through an observable. Observables can be a bit awkward to work with at first, but they're worth the effort to learn because you can use them to create faster and more stable web applications. Updating a control without depending on change detection is just one of many things they can do.

Here's [a short description of using observables with OnPush](http://stackoverflow.com/questions/35386822/changedetectionstrategy-onpush-and-observable-subscribe-in-angular-2). And, if you're curious to understand the whole change detection process better, here's [a longer article that goes into a lot more detail](https://blog.thoughtram.io/angular/2016/02/22/angular-2-change-detection-explained.html).
