### ISSUE TITLE
onChange() triggers twice

### ISSUE THREAD

**Issue by JustinPhung** [dschnelldavis/angular2-json-schema-form#11]
Everytime I change something onChange method triggers twice.

**Comment by dschnelldavis** [comment]
onChange triggers twice when Angular 2 is in development mode. Because this library is still under heavy development, I've chosen to leave the example playground in development mode for the time being. If you want to run the example playground in production mode, download the latest updates from Git Hub, then edit src/playground/main.ts and uncomment the following line (by removing the two slashes at the beginning):

```javascript
// enableProdMode();
```

For more information, [here's a description of the differences between development mode and production mode in Angular 2](http://stackoverflow.com/questions/34868810/what-is-difference-between-production-and-development-mode-in-angular2).

When you create your own app and use Angular2 JSON Schema Form as a dependency, your app will control whether it runs in development of production mode. Usually, you enable production mode by adding the following two lines to your main.ts file, above your `main()` function:

```javascript
import { enableProdMode } from '@angular/core';

enableProdMode();
```

**Comment by hk-skit** [comment]
In case you want same behavior in both dev and production build you can do something like this:
```
// In template
<json-schema-form #jsonFromSchema></json-schema-form>

// In component

..
..
@ViewChild('jsonFromSchema')
  public jsonFormSchemaRef: JsonSchemaFormComponent;
..
..
public ngOnInit(){
this._onChanges$ =
      this.jsonFormSchemaRef.onChanges
        .distinctUntilChanged((current, prev) => _.isEqual(current, prev)) // isEqual from lodash
        .subscribe(($event) => console.log('Changes -->', $event));
}

```

**Comment by Mathijs003** [comment]
With production on this still triggers twice using :  "angular2-json-schema-form": "^0.7.0-alpha.1"

@hk-skit can you provide an example or plunker? Can't seem to get your code working.
