### ISSUE TITLE
Defaults not working

### ISSUE THREAD

**Issue by tmburnell** [dschnelldavis/angular2-json-schema-form#122]
Using https://angular2-json-schema-form.firebaseapp.com/
and the below schema ... it renders but does not do anything with default.

```
{
    "type": "object",
    "properties": {
      "Input with Default": {
        "description": "should default to string1",
        "type": "string",
        "enum": ["string1", "string2", "string3"],
        "default": "string1"
      }
    }
}
```

also this example does not look like it work either: https://angular2-json-schema-form.firebaseapp.com/?set=jsf&example=jsf-fields-tabarray-value&framework=material-design

**Comment by dschnelldavis** [comment]
Yep. I turned them off for testing and forgot to turn them back on. Sorry about that.

They are working again as of version 0.5.0-alpha.14.

**Comment by jscharett** [comment]
I'm using 0.5.0-alpha.16, and seeing similar issue.  Seems that when i specify my own widgets that the defaults are never set.  Assuming it has something to do with getFirst never being called. When specifying my custom widgets, I set the type in the layout which causes 'checkInlineType' to be run

```
if (!hasOwn(newNode, 'type')) {
    newNode.type = getInputType(nodeSchema, newNode);
}
else if (!widgetLibrary.hasWidget(newNode.type)) {
    var /** @type {?} */ oldWidgetType = newNode.type;
    newNode.type = getInputType(nodeSchema, newNode);
    console.error("error: widget type \"" + oldWidgetType + "\" " +
        ("not found in library. Replacing with \"" + newNode.type + "\"."));
}
else {
    newNode.type = checkInlineType(newNode.type, nodeSchema, newNode);
}
```
Then, in that function, it appears to only do the getFirst for checkbox/radio(s)
```
function checkInlineType(controlType, schema, layoutNode) {
    if (layoutNode === void 0) { layoutNode = null; }
    if (!isString(controlType) || (controlType.slice(0, 8) !== 'checkbox' && controlType.slice(0, 5) !== 'radio')) {
        return controlType;
    }
    if (JsonPointer.getFirst([
```
Is this by design?  Or maybe I am jsut not understanding how defaults are set yet. How do you set default Value for a custom widget?

**Comment by jscharett** [comment]
Correction.  Appears defaults not working at all on 0.5.0-alpha.16

**Comment by jscharett** [comment]
Ugh, long day.  Turns out I was hitting the wrong service endpoint.  My apologies.  All is well
