### ISSUE TITLE
Error: MaterialModule is not an NgModule

### ISSUE THREAD

**Issue by fredbi** [dschnelldavis/angular2-json-schema-form#128]
I get this error when building my app after including the JsonSchemaFormModule in my import in app.module.ts.

- installed v0.5.6 via npm
- Use ng build with @angular/cli 1.49
- Use @angular/xxx@4.4.6

**Comment by dschnelldavis** [comment]
Oops. I thought I got rid of all the references to MaterialModule.

But it turns out I missed one file: [the readme](https://github.com/dschnelldavis/angular2-json-schema-form/blob/master/README.md).

So follow the instructions in the [new readme](https://github.com/dschnelldavis/angular2-json-schema-form/blob/master/README.md) I just uploaded to GitHub, and that should fix your problem.

(The readme on NPM is still incorrect, but it will get updated the next time I publish a new release, probably in a day or two.)
