### ISSUE TITLE
Getting typescript error upon installation

### ISSUE THREAD

**Issue by tsgautier** [dschnelldavis/angular2-json-schema-form#13]
```
> angular2-json-schema-form@0.3.0-alpha.26 tsc /Users/tgautier/src/angular2-json-schema-form
> tsc

../../node_modules/@types/protractor/index.d.ts(11,34): error TS2304: Cannot find name 'webdriver'.
../../node_modules/@types/protractor/index.d.ts(12,27): error TS2304: Cannot find name 'webdriver'.
../../node_modules/@types/protractor/index.d.ts(13,32): error TS2304: Cannot find name 'webdriver'.
../../node_modules/@types/protractor/index.d.ts(14,27): error TS2304: Cannot find name 'webdriver'.
...
```

Darwin Kernel Version 16.3.0, node version 7.4.0, npm version 4.0.5

**Comment by dschnelldavis** [comment]
Hmmm. I don't think this is a problem with Angular2 JSON Schema Form. I just ran the example playground on an identical configuration (same Darwin, node, and npm versions), and it worked fine. This library doesn't use Protractor or Selenium WebDriver, so I don't see any way Angular2 JSON Schema Form itself could cause those errors.

Based on the error messages, it looks like its a problem with [the TypeScript definition files for Selenium WebDriver](https://www.npmjs.com/package/@types/selenium-webdriver). The first thing I would check is to make sure you're using the latest versions of Selenium and Protractor, and the latest @types type definitions for them.

My best guess is that Angular2 JSON Schema Form is calling the TypeScript compiler (TSC), and the compiler can't find the type definitions it needs, so it throws those errors. To fix it, I suspect you just need to make sure you have the correct TypeScript definitions for the versions of Selenium and Protractor you're using. I don't have much experience with Selenium or Protractor though, so if it's more complicated than that, you should Google Angular2 Selenium Protractor TypeScript configuration (or some variation) for more information.

If you determine that the problem really was caused by Angular2 JSON Schema Form, post again with instructions about how to recreate the problem, and I'll re-open this issue and look into into it more.

Thanks!

-David
