### ISSUE TITLE
How to render Collapsible/Expandable sections for sub-objects

### ISSUE THREAD

**Issue by prnitin** [dschnelldavis/angular2-json-schema-form#133]
## Issue type
I'm submitting a (check one):
<pre><code>
[ ] Bug report
[ ] Feature request
[ ] Regression (something that used to work, but stopped working in a newer version)
[x] Support request
[ ] Documentation issue or request
</code></pre>

## Current behavior
All objects are rendered sequentially. If the schema is very large, it results in a very large form.

## Expected behavior
If there is option to make sections as expandable/collapsible, then the form will be smaller and users can skip section that are not applicable and scroll faster to the sections they are interested in.

## Environment
<pre><code>
OS name & version: Windows 10
Browser name & version:: Chrome
Angular version: 4
Angular JSON Schema Form version:
Other relevant software or packages: material.angular.io

**Comment by dschnelldavis** [comment]
You can do this by adding `"expandable"=true` in your layout. By default, expandable sections are initially hidden. To change this behavior, also add `"expanded"=true`.

Expandable sections should have a triangle next to their titles, which you can click on to expand/hide the section. However, this triangle wasn't displaying due to a bug, which has been fixed as of version 0.6.0-alpha.5.

To see an example of how expanding sections work, take a look at the `Notes` section at the bottom of the default example in the [demonstration playground](https://angular2-json-schema-form.firebaseapp.com).

**Comment by VirusDEAD** [comment]
Can we get it for section to have an arrow like array does?
This requires a title so the user has something to click on. The title does not seem clickable :(
```
{
   "type": "section",
    "title": "Stats",
    "expandable": true,
    "expanded": true,
    items :[
        { "key": "some_key" },
        ...
     ]
}
```

**Comment by person2713** [comment]
Can I collapse or expande all form that was generated by library? Or may be it is possible expande and collapse object?
