### ISSUE TITLE
What about flex-layout?)

### ISSUE THREAD

**Issue by Freest10** [dschnelldavis/angular2-json-schema-form#26]
Hello, I want use flex-layout - https://github.com/angular/flex-layout instead of bootsrap in your schema-form. How can I import it in your project (not change code of modules) that I can update your project without problem?
Thx)

**Comment by dschnelldavis** [comment]
Good question. I've been playing with flex-layout too, and trying to figure out a sensible way to integrate it into a JSON Form layout, to use in conjunction with the Angular Material framework. I haven't figured out a good solution yet, but I am working on it. I'll leave this open for now, and update it when I figure something out.

In the meantime, if you have any implementation suggestions, let me know.

**Comment by agborkowski** [comment]
🍺

**Comment by dschnelldavis** [comment]
OK, this feature should be fully working now.

The default example in the demonstration playground shows how to specify flex-layout and fxLayout values in the form layout.

If you use the Material Design framework, it uses [Angular flex-layout](https://github.com/angular/flex-layout/wiki/API-Documentation), which uses all values and gives you a few more options for finer control.

If you use Bootstrap, or something else, it falls back to plain [flexbox/CSS flexible boxes](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Using_CSS_flexible_boxes) which uses flex-layout values only, and ignores any fxLayout settings. This is lighter-weight, since it requires no additional javascript, but should still be compatible with modern browsers.
