### ISSUE TITLE
How to create server validation?

### ISSUE THREAD

**Issue by witold-gren** [dschnelldavis/angular2-json-schema-form#28]
Hi. Your package is realy nice! 😀 It is very helpful! However I have question.. how to add server validation? I created django package which create json from django forms. This package work with django rest framework.. but i don't have idea how to use specific validations for field.

**Comment by dschnelldavis** [comment]
Thanks!

This is a client side library, so server-side validation is up to you, though I definitely recommend it, because a determined hacker can easily bypass anything on the front-end.

For Node, or any other flavor of JavaScript, I would recommend [AJV](http://epoberezkin.github.io/ajv/). That's the JSON Schema validator this library uses, which I like very much.

Django is in Python though, which I have less experience with. There is a [jsonschema library for Python](https://pypi.python.org/pypi/jsonschema), so I might start there.

As a general strategy, I'd start by learning about the [JSON Schema format](https://spacetelescope.github.io/understanding-json-schema/index.html) itself. Then use the same JSON Schema to first create and validate the form on the front end, then again to validate the data a second time on the server, where the validation can't be bypassed. Because you're using Python, you'll have to use a different JSON Schema validation library on the server, but you can still use the same JSON Schema on both the front-end and the server.

**Comment by witold-gren** [comment]
Thanks for your response. I understand how to create server validations. But my problem is, how to call from form to my rest endpoint and validate this field when somebody writes something. :) I didn't find in angular component any method to check my form.

**Comment by pablochud** [comment]
Can You give me a hand, how to create json from django forms that could be used with angular2-json-schema-form in frontend?

**Comment by witold-gren** [comment]
Hi.. today/tomorrow I will push my package (first version) on github.. but this is alpha version.. and don't have more tests. Generally this is not simple.. and of course I update a lot of function in angular2-json-schema-form package because I needed more functionality. If this package will not in GitHub tomorrow please send mi request ;)
