### ISSUE TITLE
Not work with angular-cli

### ISSUE THREAD

**Issue by empirefox** [dschnelldavis/angular2-json-schema-form#3]
It always fails with Error: moduleId should be a string in "TabsComponent". I can make it work after removing `moduleId` from dist/widgets/. But fail to start the playground after removing `moduleId` from source.

**Comment by dschnelldavis** [comment]
Check the new version - this should be fixed now.

I ran into a similar conflict (though with Meteor, not with Angular CLI), and refactored all components to include their HTML and CSS inline, and removed all references to moduleId.

Please try it and let me know if it works with Angular CLI. If not, send me more details about your setup (OS, Browser, version #s, etc.) and I'll see if I can recreate it.

**Comment by empirefox** [comment]
Same error here. `moduleId` is still here.
Chromium	55.0.2883.87  Built on Ubuntu , running on Ubuntu 16.10 (64 bit)
ng -v
```console
angular-cli: 1.0.0-beta.24
node: 6.9.1
os: linux x64
@angular/common: 2.4.0
@angular/compiler: 2.4.0
@angular/core: 2.4.0
@angular/forms: 2.4.0
@angular/http: 2.4.0
@angular/platform-browser: 2.4.0
@angular/platform-browser-dynamic: 2.4.0
@angular/router: 3.4.0
@angular/compiler-cli: 2.4.0
```
default tsconfi.json by angular-cli
```json
{
  "compilerOptions": {
    "baseUrl": "",
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": ["es6", "dom"],
    "mapRoot": "./",
    "module": "es6",
    "moduleResolution": "node",
    "outDir": "../dist/out-tsc",
    "sourceMap": true,
    "target": "es5",
    "typeRoots": [
      "../node_modules/@types"
    ]
  }
}
```

**Comment by empirefox** [comment]
I want to change module to commonjs and try again. So i try to remove other deps which are not commonjs. But after clean, i encounter another error: `ERROR in JsonSchemaFormModule is not an NgModule`. Maybe it is caused by [this](https://github.com/angular/angular/blob/master/CHANGELOG.md#note).

**Comment by dschnelldavis** [comment]
Yep, I thought I got rid of all the module.id's, but it looks like I missed some.

I accepted your pull request, which fixed the module.id problem, but then wouldn't compile correctly for other reasons (possibly because of a combination of your fixes with other recent changes I made). So I switched the compiler from ngc back to tsc, and now it compiles correctly again. I'd like to switch back to ngc eventually, but I think I'll wait a while - as this isn't the first problem I've had with ngc, and it looks like they're still working out a few bugs.

I also uploaded your fixes to NPM. The latest version is 0.3.0-alpha.11. (The npmjs.com page incorrectly shows 0.3.0-alpha.8 as the latest - I'm not sure why. But despite that, 'npm show angular2-json-schema-form version' shows the correct version, and if you put "0.3.0-alpha.11" in your package.json, it installs fine.) Please try it and let me know if it fixes your problem.

If it doesn't, I'll install Angular-CLI on my system and run some more tests to see if I can figure it out.

Thanks!

**Comment by empirefox** [comment]
It works well on v0.3.0-alpha.11 and v0.3.0-alpha.13 with src. The compiler always hits me down too, i think src is a better choice when bad thing happens.

**Comment by dschnelldavis** [comment]
Excellent. Glad it's working for you.

I expect to be making a lot more changes soon, especially to the Material Design framework. Let me know if you have any other problems in the future. And thanks gain for the help!
