### ISSUE TITLE
It has any data to [data] when array is null

### ISSUE THREAD

**Issue by qwe852147** [dschnelldavis/angular2-json-schema-form#33]
I want to send a data vis [data]  but my data has a null array .
When  I send this data ,it pop a error which is there have a null .

Any solution can solve it whitout remove the array or give the array "" string

**Comment by dschnelldavis** [comment]
Hmmm. Yes, currently setting values to null removes the item from the returned object. This is partly because a user wanting _not_ to submit a filed generally leaves that field empty, so the library interprets "" (an empty string) as undefined, even though that's not technically correct.

Can you give me a more precise use-case example of the data you expect to be entered (or not), and how you want it to be interpreted?

**Comment by qwe852147** [comment]
Sorry it too slower to provide.

The data will be data which will be following
User role will be empty array before be assigned

```
userArray:{
    [
         user_id:"000",
         user_name:"test",
         user_role:[]
    ],
   [
         user_id:"001",
         user_name:"test2",
         user_role:["reviwer","reporter"]
    ]
```
}

**Comment by dschnelldavis** [comment]
This appears to work fine.

Paste the following in the [demonstration playground](https://angular2-json-schema-form.firebaseapp.com/), and it it will create a functional form. It even allows array input for for the first user's user_role, despite the initial null value.

You could also include your own schema or form layout to customize the form a lot more. But for a first pass, even the form it creates in data-only mode works surprisingly well for me.

```json
{
  "data": {
    "userArray": [{
      "user_id": "000",
      "user_name": "test",
      "user_role": null
    },{
      "user_id": "001",
      "user_name": "test2",
      "user_role": [ "reviwer", "reporter" ]
    }]
  }
}
```
