### ISSUE TITLE
Q: Why [data] isn't 2-way binding

### ISSUE THREAD

**Issue by agborkowski** [dschnelldavis/angular2-json-schema-form#51]
i have in code

````
<json-schema-form
						[schema]="jsonSchema"
						[form] = "jsonForm"
						[data]="jsonData"
``````

why `this.jsonData` wont change when i change form input data ?

update
i manualy patch value but in form view there is not ant change until i click on any other field..
this.jsfComponent.jsfObject.formGroup.patchValue({first_name: 'nowak kurwa'});

update2
//changeDetection: ChangeDetectionStrategy.OnPush, helps how to overide or solve problem with update data model from parent component ??

**Comment by tmburnell** [comment]
@dschnelldavis since you marked this as an enhancement ... does that mean you just have not got to it yet? or is there a specific reason it is not there?

**Comment by tmburnell** [comment]
This is not a long term answer but might be a patch till this tool supports 2-way binding. 

I created a wrapper that does some default config for me and added this:
```
    @Input() data: any;
    @Output() dataChange: EventEmitter<string> = new EventEmitter();

    onChange($event) {
        if(Object.keys($event).length > 0 && JSON.stringify($event) !== JSON.stringify(this.data)) {
            this.dataChange.next($event);
        }
    }
```

At a glance to appears to work.  just note that change seems to first a bunch and even first once were the data is an empty object (explaining the length check at the beginning).   Also not if you fire when the data does not change then you get into an infinite loop.

**Comment by dschnelldavis** [comment]
@tmburnell 

2-way binding wasn't something I considered when I first built this library. Even though I do now see the benefit, and agree that it's something the library should support, I think it's going to take quite a bit of rewriting to support it properly.

At the moment, any change in the inputs is treated as a change in the form definition (which is true if either the schema or layout has changed), and causes the entire form to be re-rendered (and, as a side-effect, causes any selected form control to lose focus, which is very annoying if a user is in the process of entering data).

If you want live data _output_ from the form, that's already supported through the `onChanges` output, which updates in real-time on every keypress, very similar to the `dataChange ` output you describe above. The difficult part of supporting full 2-way binding is adding live data _input_, to update the data displayed in the form.

To properly support 2-way binding, the data input will have to be evaluated separately, and just cause the appropriate control values to be updated (ideally without causing the selected form control to lose focus, so the user can continue to enter data, even while the form is being updated).

I think I know how to do it, I just haven't had time.

So it's an enhancement not because it isn't important—I agree that it is—but because it wasn't something the library was originally designed to support.

**Comment by tmburnell** [comment]
ok, that is totally fine. I was just making sure it was not removed for a specific reason. 

the code snippet that i provided above bound my onChange to your event of onChange.  so there was no coding changes needed in your stuff.

**Comment by dschnelldavis** [comment]
Starting with version 0.6.0-alpha.2, Angular JSON Schema Form now supports 2-way data binding!

You can check the readme for more details.
