### ISSUE TITLE
Data-only mode select

### ISSUE THREAD

**Issue by zimdero** [dschnelldavis/angular2-json-schema-form#56]
Hello how can i do select input in data-only mode ? is it posible or not

**Comment by agborkowski** [comment]
did u try push {data : { field: [a,b,c]}} ?

**Comment by zimdero** [comment]
sorry but what did you mean push ? 
simple to add like that 
Ex: 
`exampleJsonObject = {
  "data": {
    "field": ["a","b","c"]
  }
}`
this don't work because it will create input of type array but not select

**Comment by dschnelldavis** [comment]
There is no specific setting to activate data-only mode. The library automatically falls back to data-only mode if it cant find any inputs with a schema or form layout. So to "select" it, just don't input a schema or layout.

In your example, there is no way to tell the library to create a select control from the`data` input alone, because the select control needs a list of possible values to select from. You can specify that list in a `schema` by using an `enum`, or in a `form` layout by using a `titleMap`, but you need one or the other—there's no way to do it with only the form data.

**Comment by Dimich-x33** [comment]
Hello,
The `data-only` mode does not work properly.
Can you help me with it?

```
data = { first_name: 'ABC', second_name: 'ABC' };

<json-schema-form [(ngModel)]="data">
</json-schema-form>
```

I'm always getting errors like:
`ERROR Error: no schema with key or ref "http://json-schema.org/draft-06/schema#"`
and
`Cannot read property 'reset' of null`
