### ISSUE TITLE
Form always invalid if has readonly attributes.

### ISSUE THREAD

**Issue by Thorski** [dschnelldavis/angular2-json-schema-form#57]
If I set readonly to true in the schema, the value is not editable but is displayed.   This is correct.
But when the form is submitted, the event is always null.  And when other fields are edited, the
validationErrors() is called with:
  should have required property 'id'

How can I make this work?   

Also, how can I make the submit button disabled if the form is invalid or unchanged?

detailSchema = {
      "type": "object",
      "title": "Details",
      "properties": {
        "name": {
          "title": "Name",
          "type": "string",
          "description": "Item Name.",
        },
        "id": {
          "title": "ID",
          "type": "string",
          "description": "ID.",
          **"readonly": true,**
        },
      },
      "required": [
        "name",
        "id",
      ]
 };

**Comment by dschnelldavis** [comment]
Try this:

```json
{
  "type": "object",
  "title": "Details",
  "properties": {
    "name": {
      "title": "Name",
      "type": "string",
      "description": "Item Name."
    },
    "id": {
      "title": "ID",
      "type": "string",
      "description": "ID.",
      "default": "123",
      "readonly": true
    }
  },
  "required": [ "name", "id", ]
}
```

If you set a required field to read-only, it _must_ also have a default value. Otherwise the field is empty but un-editable (as you saw), so there's no way to enter a value.

If the field does not have a default value, then it muse either be editable (so the user can enter a value), or not required (so the field won't need one).

Disabling the submit button if the form is invalid is being tracked on #77 . It's on my to-do list and should be added soon.

**Comment by Thorski** [comment]
Thanks, this helps.   Although I have (always) a value in the data, so I didn't think it should need a default.
