### ISSUE TITLE
radio button not working

### ISSUE THREAD

**Issue by user2345e** [dschnelldavis/angular2-json-schema-form#60]
When I use the schema below. The $event from on submit returns null no matter the values I input. Additional error in console occurs when selecting one of the radio buttons. JSON and error are below

```
{
   "schema":{
      "rating":{
         "required":true,
         "type":"array",
         "title":"title",
         "items":{
            "type":"string",
            "minItems":1,
            "maxItems":1,
            "enum":[
               "1",
               "2",
               "3"
            ]
         }
      }
   },
   "form":[
      {
         "key":"rating",
         "type":"radios"
      }
   ]
}
```

```
ERROR TypeError: value.forEach is not a function
    at FormArray.webpackJsonp../node_modules/@angular/forms/@angular/forms.es5.js.FormArray.setValue (forms.es5.js:3577)
    at JsonSchemaFormService.webpackJsonp../node_modules/angular2-json-schema-form/angular2-json-schema-form.es5.js.JsonSchemaFormService.updateValue (angular2-json-schema-form.es5.js:5727)
    at RadiosComponent.webpackJsonp../node_modules/angular2-json-schema-form/angular2-json-schema-form.es5.js.RadiosComponent.updateValue (angular2-json-schema-form.es5.js:6536)
    at Object.eval [as handleEvent] (RadiosComponent.html:53)
    at handleEvent (core.es5.js:11914)
    at callWithDebugContext (core.es5.js:13206)
    at Object.debugHandleEvent [as handleEvent] (core.es5.js:12794)
    at dispatchEvent (core.es5.js:8814)
    at core.es5.js:9406
    at HTMLInputElement.<anonymous> (platform-browser.es5.js:2687)
```

**Comment by dschnelldavis** [comment]
There are two separate problems here. One is a bug in how the library handled arrays, which has been fixed as of version 0.5.0-alpha.5.

The other is that in the example above, the elements of the `schema` and `form` inputs don't match correctly. As written, the `form` property says to use a `radios` control to represent the array element, which won't work.

Arrays are usually represented by an `array` control, which displays as a list of child controls inside it, one for each array element. Those controls can then be added, removed, and reordered (unless prevented by constraints in the `schema` or `form`). The exception is if the array only accepts specific values from an enum list or titleMap, in which case the whole array can be represented by a single `checkboxes` control, which displays as a list of checkboxes instead.

Because a single `radios` control can only return one value (unlike a `checkboxes` control, which can return multiple values), a `radios` control cannot directly represent an entire array, though it can represent array elements.

Here are a few alternative `schema`/`form` combinations that will work, depending on what you want your final data to look like. Each example also contains a `data` input, which shows how the final output object will be structured.

## 1. Using your schema, and a form to match:
```json
{
  "data": {
    "rating": [ "1", "2" ]
  },
  "schema": {
    "rating": {
      "required": true,
      "type": "array",
      "title": "title",
      "items": {
        "type": "string",
        "minItems": 1,
        "maxItems": 1,
        "enum": [ "1", "2", "3" ]
      }
    }
  },
  "form": [
    {
      "key": "rating",
      "type": "array",
      "items": {
        "key": "rating[]",
        "type": "radios"
      }
    }
  ]
}
```
In this case, the  `minItems` and `maxItems` keys are ignored, because they apply to the `string` element, which is always a single value anyway. (Example 3, below, shows how to apply `minItems` and `maxItems` to the array instead.) Without the form input, the `enum` in this schema would normally cause it to display as one `checkboxes` control, but the form input overrides that and causes it to display as list of separate `radios` controls instead.

## 2. Using your form, and a schema to match:
```json
{
  "data": {
    "rating": "1"
  },
  "schema": {
    "rating": {
      "required": true,
      "type": "string",
      "title": "title",
       "enum": [ "1", "2", "3" ]
    }
  },
  "form": [
    {
      "key": "rating",
      "type": "radios"
    }
  ]
}
```
This displays the single `radios` control specified in your form. But since the control only returns one value, the `array` in the schema has been replaced by a `string` element, which likewise takes one value. Without the form input, this schema would display a `select` control. But `radios` and `select` controls return exactly the same type of data (a single item from a predetermined list), so in practice you can use whichever you like better. (`Radios` may visually _look_ like `checkboxes`, but under the hood, they _act_ like `select` controls. So `radios` and `select` controls are usually interchangeable, but `checkboxes` are not, because they return a different type of data.)

## 3. Something in between—using an array constrained by minItems and maxItems:
```json
{
  "data": {
    "rating": [ "1" ]
  },
  "schema": {
    "rating": {
      "required": true,
      "type": "array",
      "title": "title",
      "items": {
        "type": "string",
        "enum": [ "1", "2", "3" ]
      },
      "minItems": 1,
      "maxItems": 1
    }
  },
  "form": [
    {
      "key": "rating",
      "type": "array",
      "items": {
        "key": "rating[]",
        "type": "radios"
      }
    }
  ]
}
```
If you want to constrain your array with `minItems` and `maxItems`, put them in the `array` object itself (not inside `items`). This defeats the usual purpose of having an array, which is to collect multiple values together, but if you need your data structured that way, this is how to do it.
