### ISSUE TITLE
IE 11 Select no event triggered 

### ISSUE THREAD

**Issue by boydy12** [dschnelldavis/angular2-json-schema-form#80]
Hello,

Found a bug with IE 11 and the drop down (select). The change function does not pick up the event when a user selects an option. This is due to this issue:

https://stackoverflow.com/questions/41940110/angular-2-why-do-i-need-to-use-change-instead-of-input-in-ie-11-input-rang

If possible please could this be fixed in earlier releases. (0.3.0-alpha.27)

Thanks

**Comment by dschnelldavis** [comment]
This should be fixed as of 0.5.0-alpha.5.

However, currently I have no Windows machine to test on. So could you please take a look at the [demonstration playground](https://angular2-json-schema-form.firebaseapp.com/) in IE and let me know if changing select values works correctly, for both the Material Design and Bootstrap frameworks?

This should take less than a minute to test. Just change the state from 'NV' to something else, and confirm that your change shows in the Form Output below the form. Then change the framework form Material Design to Bootstrap, and check it again. If both work, this bug should be 100% fixed.

Also, due to the way NPM handles versions, I don't have the ability to change earlier releases.

You could make a customized version of the earlier release though.

If you're using Bootstrap, all you have to do is change one line in the [Select Component](https://github.com/dschnelldavis/angular2-json-schema-form/blob/master/src/lib/src/widget-library/select.component.ts) from
`(input)="updateValue($event)"`
to
`(change)="updateValue($event)"`

If you're using material design, there are more changes, so you may want to just replace the entire [Material Select Component](https://github.com/dschnelldavis/angular2-json-schema-form/blob/master/src/lib/src/framework-library/material-design-framework/material-select.component.ts) with the updated version.
