### ISSUE TITLE
onClick event in actions don't seem to work

### ISSUE THREAD

**Issue by kvriesacker** [dschnelldavis/angular2-json-schema-form#9]
I couldn't find an example in your library where the onClick event for custom buttons seem to work.
Example:
{
      "type": "actions",
      "items": [
        {
          "type": "submit",
          "style": "btn-info",
          "title": "Do It!"
        },
        {
          "type": "button",
          "style": "btn-danger",
          "title": "Noooooooooooo",
          **"onClick": "sayNo()"**
        }
      ]
    }

**Comment by dschnelldavis** [comment]
They didn't work before, but they should now.

I updated the buttons to use custom onClick actions, if available. This fix is now available on both GitHub and NPM starting in version 0.3.0-alpha.26. I haven't added this option to any other control types yet, but tell me if you need it, and I can easily do so.

I tested this as working in the playground, in the set "JSONForm compatibility examples", example "Using event handlers".

It strikes me that there should be a more elegant way to handle this in Angular, without putting executable code directly inside a schema - which is why I didn't initially add this feature. However, I don't know what the best alternative would be instead. Also, one of the design goals of this project is backward-compatibility with JSON Form, which includes this feature, so obviously we should support it.

Anyway, please test the new version and let me know if it works for you.

**Comment by dschnelldavis** [comment]
Since I haven't heard back, I'm going to assume this issue is fixed and close it.

If you have additional problems, post again and we can re-open it if necessary.

Thanks!

**Comment by tthtrifork** [comment]
I can't get this to work using v0.4.0-alpha.18.
typeof this.options.onClick === 'function' is returning false because typeof this.options.onClick is 'string'

If I break when the button is pressed I can replace the onClick with a pointer to the function I need to call and then it works - so guess the problem is that the method isn't set correctly.

Where can I find a working example preferably as an angular2 version.

**Comment by i-am-dror** [comment]
actually, it's not working, you can have a look at the kitchen sink demo, the "Noooooooooooo" button does nothing.
also, style does not apply to it and on the submit button.

**Comment by subratawebops** [comment]
Any progress on this?

**Comment by person2713** [comment]
try this example:
`public layout = [
      '*',
              {
                type: 'button',
                title: 'Save',
                onClick: (event) => {
                  console.log('onClick', event);
                }
              }
     ];`
